"""
Reading Chainlink price feeds directly from chain, and testing whether they are
actually the reference Polymarket settles against.

WHY THIS EXISTS. Polymarket's crypto "Up or Down" markets resolve on
"the time-weighted average price (TWAP) of X, generated by Chainlink" with a
resolution source of data.chain.link/streams/<pair>-twap-60s-streams. Every gap
this project has recorded so far was computed from Hyperliquid's last trade, which
is a different number from a different venue. On a contract decided by a $20 move
in Bitcoin, that is not a rounding difference - it decides the outcome.

THE DISTINCTION THAT MATTERS, AND IT IS EASY TO MISS. Chainlink sells two separate
products:

  DATA FEEDS    on-chain aggregator contracts, updated when the price moves past a
                deviation threshold OR a heartbeat elapses. Free to read by anyone
                with an RPC endpoint. NOT continuous - between updates the value on
                chain is stale by design.
  DATA STREAMS  pull-based, low-latency, sub-second, reports signed off-chain and
                verified on demand. This is what "twap-60s-streams" refers to, and
                access normally requires credentials.

So the on-chain feed is NOT the stream. It is the closest freely-readable relative,
and whether it is a usable proxy is an empirical question about how often it
updates and how far it drifts from spot between updates. That question is what
this file answers, rather than assuming either way.

HOW THE READ WORKS, without web3 or any dependency. A Chainlink aggregator
implements AggregatorV3Interface. Two calls are needed:

    decimals()          selector 0x313ce567  -> uint8
    latestRoundData()   selector 0xfeaf968c  -> (uint80 roundId, int256 answer,
                                                 uint256 startedAt,
                                                 uint256 updatedAt,
                                                 uint80 answeredInRound)

The return is five 32-byte words, ABI-encoded and right-aligned, so decoding is
slicing the hex and reading integers. `updatedAt` is the crucial one: it says when
the on-chain value was last written, and therefore how stale the price is RIGHT
NOW. A feed that updates every few minutes is usable for five-minute markets; one
that updates hourly is not.
"""
import datetime
import json
import sys
import time
from concurrent.futures import ThreadPoolExecutor

import requests

UA = {'User-Agent': 'Mozilla/5.0'}
FEEDS_DIR = 'https://reference-data-directory.vercel.app/feeds-matic-mainnet.json'

# Public Polygon RPCs. Several are listed because free endpoints rate-limit and
# go down; the reader falls through them rather than failing on the first refusal.
RPCS = [
    'https://polygon-rpc.com',
    'https://polygon-bor-rpc.publicnode.com',
    'https://rpc.ankr.com/polygon',
    'https://polygon.llamarpc.com',
]

SEL_LATEST = '0xfeaf968c'
SEL_DECIMALS = '0x313ce567'

# The assets Polymarket runs Up/Down markets on
WANT = ['BTC', 'ETH', 'SOL', 'XRP', 'DOGE', 'BNB', 'ZEC', 'HYPE']


def rpc_call(to, data, rpcs=None, tries=2):
    """eth_call against the first RPC that answers."""
    payload = {'jsonrpc': '2.0', 'id': 1, 'method': 'eth_call',
               'params': [{'to': to, 'data': data}, 'latest']}
    for rpc in (rpcs or RPCS):
        for _ in range(tries):
            try:
                r = requests.post(rpc, json=payload, headers=UA, timeout=15)
                if r.status_code == 200:
                    j = r.json()
                    if 'result' in j and j['result'] not in (None, '0x'):
                        return j['result'], rpc
            except Exception:
                pass
    return None, None


def _u(hexstr, word):
    """Read the Nth 32-byte word as an unsigned integer."""
    h = hexstr[2:] if hexstr.startswith('0x') else hexstr
    chunk = h[word * 64:(word + 1) * 64]
    return int(chunk, 16) if chunk else None


def _i256(hexstr, word):
    """Read the Nth word as a SIGNED 256-bit integer. Prices are int256 and a
    negative value is meaningful (an error state), so an unsigned read would turn
    a fault into an astronomically large price."""
    v = _u(hexstr, word)
    if v is None:
        return None
    return v - (1 << 256) if v >= (1 << 255) else v


def read_feed(address):
    dec_hex, _ = rpc_call(address, SEL_DECIMALS)
    decimals = _u(dec_hex, 0) if dec_hex else 8
    raw, rpc = rpc_call(address, SEL_LATEST)
    if not raw:
        return None
    answer = _i256(raw, 1)
    updated = _u(raw, 3)
    if answer is None or updated is None:
        return None
    return {'price': answer / (10 ** decimals), 'decimals': decimals,
            'updated_at': updated, 'rpc': rpc,
            'age_s': time.time() - updated}


def find_feeds():
    """Locate the USD aggregator for each asset in Chainlink's own directory."""
    r = requests.get(FEEDS_DIR, headers=UA, timeout=30)
    r.raise_for_status()
    feeds = r.json()
    out = {}
    for f in feeds:
        # The `pair` field in this directory is ['', ''] on every entry - reading
        # the asset from it silently matched nothing and returned zero feeds. The
        # asset is in `name` ("BTC / USD") and in docs.baseAsset.
        name = (f.get('name') or '').strip()
        docs = f.get('docs') or {}
        base = (docs.get('baseAsset') or name.split('/')[0]).strip().upper()
        quote = (docs.get('quoteAsset') or
                 (name.split('/')[1] if '/' in name else '')).strip().upper()
        if quote != 'USD' or base not in WANT:
            continue
        if docs.get('shutdownDate'):
            continue                                  # retired feed
        addr = f.get('proxyAddress') or f.get('contractAddress')
        if not addr:
            continue
        if base not in out:
            out[base] = {'address': addr, 'name': name,
                         'heartbeat': f.get('heartbeat'),
                         'threshold': f.get('threshold')}
    return out


if __name__ == '__main__':
    print('=' * 104)
    print('1. LOCATING CHAINLINK AGGREGATORS ON POLYGON')
    print('=' * 104)
    try:
        feeds = find_feeds()
    except Exception as e:
        print('  feed directory failed: {}'.format(e))
        sys.exit(1)
    print('  found {} of {} wanted assets: {}'.format(
        len(feeds), len(WANT), ', '.join(sorted(feeds))))
    missing = [w for w in WANT if w not in feeds]
    if missing:
        print('  NOT on Polygon: {}'.format(', '.join(missing)))

    print('\n' + '=' * 104)
    print('2. READING THEM ON CHAIN  (the decisive column is "age" - how stale)')
    print('=' * 104)
    print('  {:6}{:>16}{:>12}{:>10}{:>14}{:>26}'.format(
        'asset', 'price', 'decimals', 'age', 'heartbeat', 'address'))
    print('  ' + '-' * 88)

    def job(kv):
        tag, meta = kv
        return tag, meta, read_feed(meta['address'])

    results = {}
    with ThreadPoolExecutor(max_workers=8) as ex:
        for tag, meta, got in ex.map(job, sorted(feeds.items())):
            results[tag] = got
            if not got:
                print('  {:6}{:>16}'.format(tag, 'READ FAILED'))
                continue
            print('  {:6}{:>16}{:>12}{:>10}{:>14}{:>26}'.format(
                tag, '{:,.4f}'.format(got['price']), got['decimals'],
                '{:.0f}s'.format(got['age_s']), str(meta.get('heartbeat') or '?'),
                meta['address'][:24]))

    print('\n' + '=' * 104)
    print('3. DOES IT AGREE WITH HYPERLIQUID SPOT?')
    print('   If the two track closely, the on-chain feed is a usable reference.')
    print('   If it lags badly, it is a different number and cannot stand in for')
    print('   the TWAP stream Polymarket actually settles on.')
    print('=' * 104)
    sys.path.insert(0, str(__import__('pathlib').Path(__file__).resolve().parent))
    import hl_data
    print('  {:6}{:>16}{:>16}{:>12}{:>10}'.format(
        'asset', 'chainlink', 'hyperliquid', 'difference', 'cl age'))
    print('  ' + '-' * 62)
    for tag in sorted(results):
        got = results[tag]
        if not got:
            continue
        try:
            bars, _ = hl_data.get_candles(tag, '1m', 1, refresh=True)
            spot = [b['c'] for b in bars if b['c'] > 0][-1]
        except Exception:
            continue
        diff = got['price'] / spot - 1.0
        print('  {:6}{:>16}{:>16}{:>12}{:>10}'.format(
            tag, '{:,.4f}'.format(got['price']), '{:,.4f}'.format(spot),
            '{:+.3%}'.format(diff), '{:.0f}s'.format(got['age_s'])))
    print("""
  HOW TO JUDGE THIS. A difference of a few basis points with a fresh timestamp
  means the on-chain feed is tracking the market and can serve as the reference.
  A difference of tenths of a percent, or an age in the thousands of seconds,
  means the feed only updates on a deviation threshold and sits stale in between -
  in which case it is NOT a usable stand-in for a 60-second TWAP on a 5-minute
  market, and the honest conclusion is that the exact settlement price is not
  freely obtainable.""")
