// Bundles src/lib/exportKit.ts (the estimate, the shopping-list CSV and the contractor price
// math) into server/generated/export-kit.mjs, so the server makes paid exports and prices
// contractor kitchens with the same code the editor runs. The output has no imports at all:
// the catalog registry is swapped for a plain map (src/lib/kit/catalogShim.ts), so neither
// zustand nor React end up in the server.
//
//   node scripts/build-kit.mjs     (npm run build, npm run api and npm test run it for you)
//
// The output is generated, so it is gitignored; deploy-local copies it with server/.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const shim = path.join(root, 'src/lib/kit/catalogShim.ts');
const registry = path.join(root, 'src/store/useCatalog.ts');
const outfile = path.join(root, 'server/generated/export-kit.mjs');

const aliasRegistry = {
  name: 'kit-registry-shim',
  setup(b) {
    b.onResolve({ filter: /useCatalog$/ }, (args) => {
      const target = path.resolve(args.resolveDir, args.path) + '.ts';
      return target === registry ? { path: shim } : undefined;
    });
  },
};

const result = await build({
  entryPoints: [path.join(root, 'src/lib/exportKit.ts')],
  outfile,
  bundle: true,
  platform: 'neutral',
  format: 'esm',
  target: 'node20',
  plugins: [aliasRegistry],
  metafile: true,
  logLevel: 'warning',
  legalComments: 'none',
  banner: { js: '// GENERATED by scripts/build-kit.mjs from src/lib/exportKit.ts. Do not edit.' },
});

// Fail loudly if anything outside src/ got pulled in (a store, React, three…).
const outside = Object.keys(result.metafile.inputs).filter((f) => !f.startsWith('src/'));
if (outside.length) {
  fs.rmSync(outfile, { force: true });
  console.error(`export kit: unexpected inputs outside src/: ${outside.join(', ')}`);
  process.exit(1);
}
const bytes = fs.statSync(outfile).size;
if (process.argv.includes('--verbose')) console.log(`export kit: ${Object.keys(result.metafile.inputs).length} modules, ${(bytes / 1024).toFixed(1)} KB → ${path.relative(root, outfile)}`);
