// Deploys the built app to a stable folder outside the repo and (re)starts the
// home server there. The database and logs are never overwritten.
//
//   npm run deploy:local        # build, copy to %USERPROFILE%\Projects\Mise, restart
//
// Env: MISE_HOME (target folder), MISE_PORT (8790), MISE_HOST (127.0.0.1).
//
// Layout of MISE_HOME:
//   app\            replaced on every deploy (dist\, server\ code, src\data\kinds.json)
//   data\mise.db    the database: kept across deploys
//   data\uploads\   uploaded models and images: kept across deploys
//   logs\           server.log
//   run-server.cmd  supervisor loop: restarts the server if it exits
//   start-server.cmd / stop-server.cmd / start-hidden.vbs

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync, spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const HOME = path.resolve(process.env.MISE_HOME || path.join(os.homedir(), 'Projects', 'Mise'));
const PORT = String(process.env.MISE_PORT || '8790');
const HOST = process.env.MISE_HOST || '127.0.0.1';
const APP = path.join(HOME, 'app');
const DEPLOYING = path.join(HOME, 'deploying');
/** Files outside server/ that the server imports at runtime (kept at the same relative path). */
const RUNTIME_FILES = ['src/data/kinds.json'];

if (process.platform !== 'win32') {
  console.error('deploy-local is written for the Windows home server. Use `npm start` elsewhere.');
  process.exit(1);
}
if (!fs.existsSync(path.join(ROOT, 'dist', 'index.html'))) {
  console.error('No build found. Run `npm run build` first (or use `npm run deploy:local`).');
  process.exit(1);
}

/** PIDs listening on PORT whose command line runs this home's server. */
function serverPids() {
  let out = '';
  try { out = execFileSync('netstat', ['-ano', '-p', 'tcp'], { encoding: 'utf8' }); } catch { return []; }
  const pids = new Set();
  for (const line of out.split(/\r?\n/)) {
    const cols = line.trim().split(/\s+/);
    if (cols[0] === 'TCP' && cols[1]?.endsWith(':' + PORT) && cols[3] === 'LISTENING') pids.add(cols[4]);
  }
  return [...pids].filter((pid) => {
    try {
      const cmd = execFileSync('powershell.exe', ['-NoProfile', '-Command',
        `(Get-CimInstance Win32_Process -Filter "ProcessId=${Number(pid)}").CommandLine`], { encoding: 'utf8' });
      return cmd.toLowerCase().includes(APP.toLowerCase());
    } catch { return false; }
  });
}

function portTaken() {
  try {
    const out = execFileSync('netstat', ['-ano', '-p', 'tcp'], { encoding: 'utf8' });
    return out.split(/\r?\n/).some((l) => { const c = l.trim().split(/\s+/); return c[0] === 'TCP' && c[1]?.endsWith(':' + PORT) && c[3] === 'LISTENING'; });
  } catch { return false; }
}

const copyTree = (from, to, skip = () => false) =>
  fs.cpSync(from, to, { recursive: true, filter: (src) => !skip(src) });

// ─── Supervisor scripts (regenerated each deploy so they track this file) ──

const NODE = process.execPath;
const SCRIPTS = {
  'run-server.cmd': `@echo off
rem Mise home server supervisor. Runs the server and restarts it if it exits.
rem Started hidden by start-hidden.vbs (at logon, or via start-server.cmd).
rem Generated by kitchen-visualizer/scripts/deploy-local.mjs - edits are overwritten.
setlocal
cd /d "%~dp0"
set PORT=${PORT}
set HOST=${HOST}
set DB_PATH=%~dp0data\\mise.db
if not exist logs mkdir logs
:loop
if exist stopped exit /b 0
if exist deploying (ping -n 3 127.0.0.1 >nul & goto loop)
rem Another instance already holds the port: leave it alone rather than spin.
netstat -ano -p tcp | findstr /R /C:":${PORT} .*LISTENING" >nul && exit /b 0
echo [%date% %time%] starting on %HOST%:%PORT% >> logs\\server.log
rem Absolute script path, so deploy-local can tell this server from other node processes.
"${NODE}" --no-warnings "%~dp0app\\server\\index.mjs" --prod >> logs\\server.log 2>&1
echo [%date% %time%] server exited with code %errorlevel%, restarting in 5s >> logs\\server.log
ping -n 6 127.0.0.1 >nul
goto loop
`,
  'start-hidden.vbs': `' Starts the Mise server supervisor with no console window.
Set fso = CreateObject("Scripting.FileSystemObject")
dir = fso.GetParentFolderName(WScript.ScriptFullName)
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = dir
sh.Run "cmd /c """ & dir & "\\run-server.cmd""", 0, False
`,
  'start-server.cmd': `@echo off
cd /d "%~dp0"
if exist stopped del stopped
wscript.exe "%~dp0start-hidden.vbs"
echo Mise is starting at http://localhost:${PORT}
`,
  'stop-server.cmd': `@echo off
rem Stops the server and its supervisor until start-server.cmd is run again.
cd /d "%~dp0"
echo.> stopped
for /f "tokens=5" %%p in ('netstat -ano -p tcp ^| findstr /R /C:":${PORT} .*LISTENING"') do taskkill /PID %%p /F >nul 2>&1
echo Mise server stopped. Run start-server.cmd to start it again.
`,
};

// ─── Deploy ────────────────────────────────────────────────────────────────

fs.mkdirSync(path.join(HOME, 'data'), { recursive: true });
fs.mkdirSync(path.join(HOME, 'logs'), { recursive: true });
fs.writeFileSync(DEPLOYING, new Date().toISOString());
try {
  const running = serverPids();
  for (const pid of running) execFileSync('taskkill', ['/PID', pid, '/F'], { stdio: 'ignore' });
  if (running.length) console.log(`Stopped running server (pid ${running.join(', ')}).`);
  else if (portTaken()) {
    console.error(`Port ${PORT} is in use by something other than this Mise install. Set MISE_PORT to a free port.`);
    process.exit(1);
  }

  const staging = APP + '.new';
  fs.rmSync(staging, { recursive: true, force: true });
  copyTree(path.join(ROOT, 'dist'), path.join(staging, 'dist'));
  copyTree(path.join(ROOT, 'server'), path.join(staging, 'server'),
    (src) => /[\\/]server[\\/](data|test)([\\/]|$)/.test(src));
  // Files outside server/ that the server imports at runtime, at the same relative paths.
  for (const rel of RUNTIME_FILES) {
    fs.mkdirSync(path.dirname(path.join(staging, rel)), { recursive: true });
    fs.copyFileSync(path.join(ROOT, rel), path.join(staging, rel));
  }
  fs.copyFileSync(path.join(ROOT, 'package.json'), path.join(staging, 'package.json'));
  let head = 'unknown';
  try { head = execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim(); } catch {}
  fs.writeFileSync(path.join(staging, 'DEPLOYED.txt'), `commit ${head}\ndeployed ${new Date().toISOString()}\nfrom ${ROOT}\n`);

  fs.rmSync(APP, { recursive: true, force: true });
  fs.renameSync(staging, APP);
  for (const [name, body] of Object.entries(SCRIPTS)) fs.writeFileSync(path.join(HOME, name), body.replace(/\r?\n/g, '\r\n'));
  console.log(`Deployed commit ${head} to ${APP}`);
} finally {
  fs.rmSync(DEPLOYING, { force: true });
}

// Start it unless the supervisor is already looping (it restarts on its own) or
// someone stopped it on purpose.
await new Promise((r) => setTimeout(r, 3000));
if (fs.existsSync(path.join(HOME, 'stopped'))) {
  console.log('Server is stopped on purpose (stopped file present). Run start-server.cmd to start it.');
  process.exit(0);
}
if (!serverPids().length) {
  spawn('wscript.exe', [path.join(HOME, 'start-hidden.vbs')], { detached: true, stdio: 'ignore' }).unref();
}

for (let i = 0; i < 30; i++) {
  await new Promise((r) => setTimeout(r, 1000));
  try {
    const res = await fetch(`http://127.0.0.1:${PORT}/`);
    if (res.ok) { console.log(`Mise is up at http://localhost:${PORT}`); process.exit(0); }
  } catch {}
}
console.error(`Server did not answer on port ${PORT} within 30s. Check ${path.join(HOME, 'logs', 'server.log')}.`);
process.exit(1);
